{"uuid": "1572fa02-294e-46dc-9ac9-f882f37891bd", "counter": 5, "stdout": "\u001b[0;31mfatal: [192.168.1.30]: FAILED! => {\"msg\": \"The field 'remote_user' has an invalid value, which includes an undefined variable. The error was: 'rpi_user' is undefined\"}\u001b[0m", "start_line": 4, "end_line": 5, "runner_ident": "6520b306-0197-4623-8b66-06016c3a0286", "event": "runner_on_failed", "pid": 29306, "created": "2020-11-29T21:47:04.248445", "parent_uuid": "50e085c0-7515-513e-de05-000000000018", "event_data": {"playbook": "/home/s/projects/raspicam/remotecam/files/setup/ansible/rpi_setup.yml", "playbook_uuid": "74043561-c215-4d1e-9e4a-ca89e4a0dcb9", "play": "all", "play_uuid": "50e085c0-7515-513e-de05-000000000006", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "50e085c0-7515-513e-de05-000000000018", "task_action": "gather_facts", "task_args": "", "task_path": "/home/s/projects/raspicam/remotecam/files/setup/ansible/rpi_setup.yml:1", "host": "192.168.1.30", "remote_addr": "192.168.1.30", "res": {"msg": "The field 'remote_user' has an invalid value, which includes an undefined variable. The error was: 'rpi_user' is undefined", "_ansible_no_log": false}, "start": "2020-11-29T21:47:04.232121", "end": "2020-11-29T21:47:04.248303", "duration": 0.016182, "ignore_errors": null, "event_loop": null, "uuid": "1572fa02-294e-46dc-9ac9-f882f37891bd"}}