{"event": "runner_on_failed", "pid": 17967, "uuid": "cf6cb95c-6a16-465e-bc34-732cf94bee72", "created": "2020-11-29T18:59:19.015754", "parent_uuid": "50e085c0-7515-846e-ae82-00000000000f", "event_data": {"playbook": "/home/s/projects/raspicam/remotecam/files/setup/ansible/initial_setup.yml", "playbook_uuid": "8e594caa-3628-47a2-aa71-ce9dd3d4fcfd", "play": "all", "play_uuid": "50e085c0-7515-846e-ae82-000000000006", "play_pattern": "all", "task": "Setup virtualenv", "task_uuid": "50e085c0-7515-846e-ae82-00000000000f", "task_action": "pip", "task_args": "", "task_path": "/home/s/projects/raspicam/remotecam/files/setup/ansible/initial_setup.yml:41", "host": "192.168.1.30", "remote_addr": "192.168.1.30", "res": {"msg": "Failed to import the required Python library (setuptools) on raspberrypi's Python /usr/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter", "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_pip_payload_NF0tNN/ansible_pip_payload.zip/ansible/modules/pip.py\", line 270, in <module>\nImportError: No module named pkg_resources\n", "invocation": {"module_args": {"virtualenv": "/home/pi/webcam/venv", "extra_args": null, "virtualenv_command": "/usr/bin/python3 -m venv", "chdir": null, "requirements": "/home/pi/webcam/requirements.txt", "name": null, "virtualenv_python": null, "umask": null, "editable": false, "executable": null, "virtualenv_site_packages": false, "state": "present", "version": null}}, "_ansible_no_log": false, "changed": false}, "start": "2020-11-29T18:59:16.586233", "end": "2020-11-29T18:59:19.015295", "duration": 2.429062, "ignore_errors": null, "event_loop": null, "uuid": "cf6cb95c-6a16-465e-bc34-732cf94bee72"}}